# A place to store useful aliases
alias ll="ls -GlFhkO"
alias la="ls -GAlFhkO"
alias gvim="mvim"
alias ffind="find . -name "
alias ffindi="find . -iname "
alias hgrep="ffind \"*.h\" | xargs grep -n"
alias dev="cd ~/Development"
alias fah="dev && cd fah_products"
alias fn="dev && cd Foundry"
